#!/usr/bin/env bash
# Date and time. Click for a calendar popup.
set -euo pipefail

case "${BLOCK_BUTTON:-}" in
  1|2|3)
    month=$(date '+%m')
    year=$(date '+%Y')
    TERM=xterm cal --color=always "$month" "$year" |
      sed -e 's/\x1b\[[7;]*m/<b><u>/g' -e 's/\x1b\[[27;]*m/<\/u><\/b>/g' |
      tail -n +2 |
      rofi -dmenu -markup-rows -no-fullscreen -no-custom \
        -theme "$HOME/.config/rofi/calendar.rasi" \
        -p "$(date '+%A, %d %B')" >/dev/null
    ;;
esac

date '+%a %Y-%m-%d %H:%M:%S'
date '+%d.%m %H:%M'
